### ISSUE TITLE
Clarify which one is the real project

### ISSUE THREAD

**Issue by oscarfv** [jcs-elpa/flx-rs#2]
This project links to https://github.com/jcs090218/flx-rs which shows Release 0.1.3 created on Nov 9 and 28 commits, while this project shows Release 0.1.1 created on Nov 4 and 49 commits.

This is very confusing: which project should I track for keeping up-to-date?

**Comment by jcs090218** [comment]
The project [jcs090218/flx-rs]() is the rust implementation of [emacs-flx]() and use to release to [crates.io](). It should not contain any elisp files.

This repo releases are only for ELPA and focused on ready to use binaries.

---

> This is very confusing: which project should I track for keeping up-to-date?

Sorry for the confusion you have. You should keep an eye on [jcs090218/flx-rs](https://github.com/jcs090218/flx-rs) if you wonder about the implementation/algorithm. If you only care about the release, you might want to watch this repo instead of the other one.

**Comment by oscarfv** [comment]
Thanks. Maybe a note on Readme.MD would be adequate?

This is a very nice extension, it offers a noticeable speed-up on ido-flx, which I use all the time. Thank you.

**Comment by jcs090218** [comment]
Done! Thanks for the advice!
